INSERT INTO CONTACTO(NOMBRE,APODO,FECHA_CREACION) VALUES ('Juan Perez', 'juacho',DATE '2010-10-10');
INSERT INTO CONTACTO(NOMBRE,APODO,FECHA_CREACION) VALUES ('Carlos Ramirez', 'calanga',DATE '2010-10-10');
INSERT INTO CONTACTO(NOMBRE,APODO,FECHA_CREACION) VALUES ('Fernando Peraza', 'fercho',DATE '2010-10-10');
INSERT INTO CONTACTO(NOMBRE,APODO,FECHA_CREACION) VALUES ('Julian Gonzalez', 'gonzo',DATE '2010-10-10');